version: '3.8'
services:
  zircon:
    extends:
      file: config.yml
      service: zircon
    build:
      context: ${ZIRCON_DIR}
      dockerfile: Dockerfile.dev
    command: ["bash", "-c", "echo test"]
    volumes:
      - ${ZIRCON_DIR}:/usr/src/app:rw
    ports:
      - "8081:8081"
      - "9870:9870"
    depends_on:
      patricia:
          condition: service_healthy
  zircon-proto:
  # Not actually using postgres, update after docker image is built
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=myriade
      - PGPORT=5431
    ports:
      - "5431:5431"
    healthcheck:
      test: "pg_isready -h localhost -p 5431 -q -U postgres"
      interval: 1s
      timeout: 1s
      retries: 100