version: '3.8'
services:
  zircon:
    extends:
      file: docker.config.yml
      service: zircon
    build:
      context: ${ZIRCON_DIR}
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "12345:12345"
  redis:
    image: redis:6.2.4
    ports:
      - "6379:6379"