FROM golang:1.16.5-buster
WORKDIR /usr/src/app
COPY ./ /usr/src/app
RUN useradd gouser --home /usr/src/app --uid 1000 
# Home directory for managing go imports
RUN chown -R gouser:gouser /usr/src/app

USER gouser
RUN go get github.com/githubnemo/CompileDaemon

# RUN go mod download

# ENTRYPOINT CompileDaemon --build="go build -o ./build/zircon cmd/main.go" --command="./build/zircon"
# CMD tail -f /dev/null