version: '3.8'
services:
  zircon:
    extends:
      file: config.yml
      service: zircon
    build:
      context: ${ZIRCON_DIR}
      dockerfile: Dockerfile.dev
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ${ZIRCON_DIR}:/usr/src/app:rw
    ports:
      - "8081:8081"
      - "9870:9870"
  # zircon_proto:
  #   image: myriadeinc/zircon_proto:724e6a8b1276d7665cc95182eb50018d5f1bcc80
  #   environment:
  #     - NODE_PATH=src/
  #   ports:
  #     - "8088:8088"
    # healthcheck:
    #   test: "curl -f http://localhost:8088 || exit 1 "
    #   interval: 3s
    #   timeout: 3s
    #   retries: 100
  redis:
    image: redis:6.2.4
    ports:
      - "6379:6379"