version: '3.8'
services:
  zircon:
    extends:
      file: docker.config.yml
      service: zircon
    build:
      context: ${ZIRCON_DIR}
      dockerfile: Dockerfile.dev
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ${ZIRCON_DIR}:/zircon:rw
    ports:
      - "8081:8081"
      - "9870:9870"
  redis:
    image: redis:6.2.4
    ports:
      - "6379:6379"