FROM golang:1.19-buster
WORKDIR /zircon
COPY ./ /zircon
RUN useradd gouser --home /zircon --uid 1000 
# Home directory for managing go imports
RUN chown -R gouser:gouser /zircon

USER gouser
RUN go get github.com/githubnemo/CompileDaemon

# RUN go mod download

# ENTRYPOINT CompileDaemon --build="go build -o ./build/zircon cmd/zircon.go" --command="./build/zircon"
# CMD tail -f /dev/null