version: '3.8'
services:
  zircon:
    extends:
      file: docker.config.yml
      service: zircon
    build:
      context: ${ZIRCON_DIR}
      dockerfile: Dockerfile
    ports:
      - "8222:8222"
      - "4990:4990"
