version: 2.1
orbs:
  docker: circleci/docker@2.0.1

jobs:
  test:
    docker:
      - image: cimg/go:1.19.2
    steps:
      - checkout
      - run:
          name: Go mod download
          command: go mod download
      - run:
          name: Go test 
          command: go test ./...

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              only: 
                - main
                - master
                - develop
      - docker/publish:
          requires:
            - test
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: 'latest'
          filters:
            branches:
              only: 
                - main
                - master
                - develop
